### ISSUE TITLE
Related works

### ISSUE THREAD

**Issue by IAMkecheng** [ilikescience/category-colors#2]
Hi Mathew, I'm glad you're interested in this colorization area. After reading your post, I think there's a very similar work called [Palettailor ](https://ieeexplore.ieee.org/document/9222351):
K. Lu et al., "Palettailor: Discriminable Colorization for Categorical Data," in IEEE Transactions on Visualization and Computer Graphics, vol. 27, no. 2, pp. 475-484, Feb. 2021, doi: 10.1109/TVCG.2020.3030406.

Hope this will be helpful.

**Comment by ilikescience** [comment]
This is interesting! I'd love to know more about the methodology but can't access the article. If you know of a blog post or breakdown of their approach, let me know!

**Comment by IAMkecheng** [comment]
Here's the paper link: https://arxiv.org/pdf/2009.02969.pdf, 
or you can find it at: http://www.yunhaiwang.net/infoVis2020/palettailor/color-palette-generation.html

**Comment by ilikescience** [comment]
Thank you! Cool to see that they used simulated annealing too.
