### ISSUE TITLE
Generate Final Colors from Target Colors

### ISSUE THREAD

**Issue by dehru** [ilikescience/category-colors#3]
Hello, i was messing around with your script.  And it looks like it generates 8 random colors to start from.  And the target colors are used for the distance calculation.

I was hoping i could supply it with some existing colors as the start colors, and then have it output the final colors calculated from those start colors.  Am I using this correctly?  

Maybe the output is confusing me because the start colors are not the target colors i provided in index.js.

Thank you

**Comment by ilikescience** [comment]
Hi! I just pushed some code that allows you to provide some fixed `providedColors` that will initiate the algorithm. The target colors are provided so that the algorithm has some direction, but based on the weights you provide the algorithm, it won't always hit those targets exactly.
